### ISSUE TITLE
Allow treatment labels to be placed alongside nodes in network plots

### ISSUE THREAD

**Issue by zhui126** [dmphillippo/multinma#15]
Hi, Phillippo,
Thank you for the excellent package. I have one little problem with the netgraph, in which the label text for each treatment is placed in the middle of the node (circle). I think it might be better to have the text placed under or at the side of the node(circle), just like the netgraph published in JAMA journals. I wonder if it is possible to change that.
Hui

**Comment by dmphillippo** [comment]
Hi Hui, that's a great suggestion - thank you! I'll look into implementing this in the next release.
David

**Comment by zhui126** [comment]
Hi, David,
Thank you for you kind reply.
Best wishes,
Hui

--------------原始邮件--------------
发件人："David&nbsp;Phillippo ***@***.***&gt;;
发送时间：2022年3月25日(星期五) 晚上11:13
收件人："dmphillippo/multinma" ***@***.***&gt;;
抄送："zhui126 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [dmphillippo/multinma] About the netgraph (Issue #15)
-----------------------------------

 

 
Hi Hui, that's a great suggestion - thank you! I'll look into implementing this in the next release.
 David

**Comment by dmphillippo** [comment]
I've added a `nudge` argument to the `plot()` method for networks - you can see an example [here](https://dmphillippo.github.io/multinma/dev/reference/plot.nma_data.html).

This will be in the next release, but if you like you can install the latest development version with this new feature like so:
```r
install.packages("multinma", repos = c("https://dmphillippo.r-universe.dev", getOption("repos")))
```
