### ISSUE TITLE
Time to event analysis

### ISSUE THREAD

**Issue by SharmaA24** [dmphillippo/multinma#18]
Hello,

Can you please tell me how we can perform ML-NMR on survival data (time-to-event) using this package? I have tried to specify the "surv" argument in the set_ipd function but it seems that it's not working.

Urgent help would be much appreciated.

Thanks!

**Comment by dmphillippo** [comment]
Hi @SharmaA24, survival outcomes are now supported in the development branch of the package. This will be released to CRAN soon, but in the meantime you can try this out by installing the development version from r-universe:
```r
install.packages("multinma", repos = c("https://dmphillippo.r-universe.dev", getOption("repos")))
```

Let me know if you do try it and have any feedback/suggestions/bugs!

**Comment by dmphillippo** [comment]
Now on CRAN, with the release of version 0.6.0
