### ISSUE TITLE
I also could not find function "inform".

### ISSUE THREAD

**Issue by sunfeng06** [dmphillippo/multinma#2]

**Comment by dmphillippo** [comment]
Hi @sunfeng06, `inform()` is imported from the [`rlang` package](https://rlang.r-lib.org/reference/abort.html). Is that what you are after, or are you seeing a bug?

**Comment by TasnimHamza** [comment]
Hi David
Plaque psoriasis example in multinma package does not work! I got this error when I fit the model 

**Chain 4: empty_nested() must be true before calling recover_memory()
[1] "Error in sampler$call_sampler(args_list[[i]]) : "             
[2] "  empty_nested() must be true before calling recover_memory()"
error occurred during calling the sampler; sampling not done
here are whatever error messages were returned**

I followed some instructions in google but it doesn't work. 
Could the problem be only on Mac?

Thanks for the help

All the best,
Tasnim
