### ISSUE TITLE
Integration issues in ML-NMR Plaque Psoriasis example

### ISSUE THREAD

**Issue by bct0022** [dmphillippo/multinma#26]
Hi, I appreciate the great effort to create the package. I have some problems while running the ML-NMR example with `multinma` package. The problem may be due to the call of density function/distribution of the covariates as below. Could any one help me figure it out? Thank you in advance.
Error 1:

ipd_summary <- pso_ipd %>% 
  group_by(studyc) %>% 
  summarise_at(vars(weight, durnpso, bsa), list(mean = mean, sd = sd, min = min, max = max)) %>% 
  pivot_longer(weight_mean:bsa_max, names_sep = "_", names_to = c("covariate", ".value")) %>% 
  # Assign distributions
  mutate(dist = recode(covariate,
                       bsa = "dlogitnorm",
                       durnpso = "dgamma",
                       weight = "dgamma")) %>% 
  # Compute density curves
  group_by(studyc, covariate) %>% 
  mutate(value = if_else(dist == "dlogitnorm",
                         list(seq(0, 1, length.out = 101)),
                         list(seq(min*0.8, max*1.2, length.out = 101)))) %>% 
  unnest(cols = value) %>% 
  mutate(dens = eval(call(first(dist), x = value, mean = first(mean), sd = first(sd))))

==============================================
Error in `mutate()`:
ℹ In argument: `dens = eval(call(first(dist), x = value,
  mean = first(mean), sd = first(sd)))`.
ℹ In group 1: `studyc = "IXORA-S"`, `covariate = "bsa"`.
Caused by error in `dnorm()`:
! formal argument "mean" matched by multiple actual arguments
Backtrace:
  1. ... %>% ...
  9. base::eval(call(first(dist), x = value, mean = first(mean), sd = first(sd)))
 10. base::eval(call(first(dist), x = value, mean = first(mean), sd = first(sd)))
 11. logitnorm::dlogitnorm(...)
 12. base::ifelse(...)
================================================

Error 2:

pso_net <- add_integration(pso_net,
  durnpso = distr(qgamma, mean = durnpso_mean, sd = durnpso_sd),
  prevsys = distr(qbern, prob = prevsys),
  bsa = distr(qlogitnorm, mean = bsa_mean, sd = bsa_sd),
  weight = distr(qgamma, mean = weight_mean, sd = weight_sd),
  psa = distr(qbern, prob = psa),
  n_int = 1000)

==============================================
Error in `pmap()`:
ℹ In index: 3.
Caused by error in `dplyr::transmute()`:
ℹ In argument: `.int_bsa = list(...)`.
ℹ In row 1.
Caused by error in `qnorm()`:
! formal argument "mean" matched by multiple actual arguments
Backtrace:
  1. multinma::add_integration(...)
 23. logitnorm (local) `<fn>`(p = `<dbl>`, mean = 0.326, sd = 0.1778)

**Comment by dmphillippo** [comment]
Hi @bct0022, I think you may have loaded the logitnorm package with `library(logitnorm)` after loading multinma? multinma adds some convenience wrappers for these functions but these only work if the logitnorm package is _not_ loaded (or if multinma is loaded afterwards).
