### ISSUE TITLE
New multinma version with time-to-event outcomes

### ISSUE THREAD

**Issue by bct0022** [dmphillippo/multinma#33]
Hi everyone,

I am trying to update the latest version of 'multinma' version for time-to-event outcomes 
Phillippo, D. M. et al. (2024). “Multilevel network meta-regression for general likelihoods: synthesis of individual and aggregate data with applications to survival analysis”. arXiv:[2401.12640](https://arxiv.org/abs/2401.12640).

update.packages("multinma")

However, I could not find the datasets and survival functions within the updated package (i.e., set_agd_surv). Could anyone share your experience?

Thanks,

**Comment by dmphillippo** [comment]
Hi @bct0022 

Despite the name, `update.packages()` is the wrong command - this updates all installed packages, not just a single specified package.

You need to use `install.packages("multinma")` to update.
