### ISSUE TITLE
Scale values in RE model are 10 but should probably be 100

### ISSUE THREAD

**Issue by jpoehl** [dmphillippo/multinma#34]
https://github.com/dmphillippo/multinma/blob/dba35ad233b342290e08aa84a0e79ce49be8ae17/vignettes/example_dietary_fat.Rmd#L101-L102

The description of the RE model specifies $\mathrm{N}(0, 100^2)$ as the prior distribution for treatment effects and intercepts, but the code uses 10, not 100, as its scale argument (unlike, for example, the FE model above).

**Comment by dmphillippo** [comment]
Well spotted, thanks!
