### ISSUE TITLE
MD or SMD

### ISSUE THREAD

**Issue by softloud** [dmphillippo/multinma#8]
Thank you for this wonderful package and all the nma tools you created for it. 

I'm sure I must've missed something really obvious, does the multinma::nma for continuous data produce estimates of mean difference or standardised mean difference?

**Comment by dmphillippo** [comment]
Hi @softloud, no conversion is done for continuous outcomes, so the results will be on the same scale as the input data (with an identity link function, or on the log scale for a log link). Does that answer your question?

**Comment by softloud** [comment]
Thanks for responding. That makes sense for `set_agd_contrast`. I've been using `set_agd_arm`. Now :thinking: I should be using `set_agd_contrast`.

**Comment by softloud** [comment]
I figured it out -- `::set_agd_arm` estimates with mean difference :)
